export enum ErrorCode {
  DATABASE_NOT_CONNECTED = 'DATABASE_NOT_CONNECTED',
  NOT_FOUND = 'NOT_FOUND',
  UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION',
  NO_ACTIVE_RUNDOWN = 'NO_ACTIVE_RUNDOWN',
  UNKNOWN = 'UNKNOWN'
}
