export enum PlayoutContentType {
  CAMERA = 'CAMERA',
  REMOTE = 'REMOTE',
  REPLAY = 'REPLAY',
  SPLIT_SCREEN = 'SPLIT_SCREEN',
  GRAPHICS = 'GRAPHICS',
  OVERLAY_GRAPHICS = 'OVERLAY_GRAPHICS',
  VIDEO_CLIP = 'VIDEO_CLIP',
  VOICE_OVER = 'VOICE_OVER',
  JINGLE = 'JINGLE',
  AUDIO = 'AUDIO',
  MANUS = 'MANUS',
  TRANSITION = 'TRANSITION',
  COMMAND = 'COMMAND',
  UNKNOWN = 'UNKNOWN'
}
