export type EventType = PanelEventType | StatusMessageEventType | DeviceEventType | RundownEventType

export enum PanelEventType {
  PANEL_LAYOUT_CONFIGURATION_CREATED = 'PANEL_LAYOUT_CONFIGURATION_CREATED',
  PANEL_LAYOUT_CONFIGURATION_UPDATED = 'PANEL_LAYOUT_CONFIGURATION_UPDATED',
  PANEL_LAYOUT_CONFIGURATION_DELETED = 'PANEL_LAYOUT_CONFIGURATION_DELETED',

  PANEL_CONFIGURATION_CREATED = 'PANEL_CONFIGURATION_CREATED',
  PANEL_CONFIGURATION_UPDATED = 'PANEL_CONFIGURATION_UPDATED',
  PANEL_CONFIGURATION_DELETED = 'PANEL_CONFIGURATION_DELETED',

  PANEL_INPUT_MODIFIER_CREATED = 'PANEL_INPUT_MODIFIER_CREATED',
  PANEL_INPUT_MODIFIER_DELETED = 'PANEL_INPUT_MODIFIER_DELETED'
}

export enum StatusMessageEventType {
  STATUS_MESSAGE = 'STATUS_MESSAGE'
}

export enum DeviceEventType {
  VIDEO_MIXER_CONFIGURATION_UPDATED = 'VIDEO_MIXER_CONFIGURATION_UPDATED'
}

export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  REHEARSE = 'REHEARSE',
  DEACTIVATED = 'DEACTIVATED'
}

export enum ActionEventType {
  ACTIONS_UPDATED = 'ACTIONS_UPDATED'
}

export enum PlayoutContentEventType {
  PROGRAM_PLAYOUT_CONTENT = 'PROGRAM_PLAYOUT_CONTENT',
  PREVIEW_PLAYOUT_CONTENT = 'PREVIEW_PLAYOUT_CONTENT'
}
