export type EventType = PanelEventType

export enum PanelEventType {
  PANEL_LAYOUT_CONFIGURATION_CREATED = 'PANEL_LAYOUT_CONFIGURATION_CREATED',
  PANEL_LAYOUT_CONFIGURATION_UPDATED = 'PANEL_LAYOUT_CONFIGURATION_UPDATED',
  PANEL_LAYOUT_CONFIGURATION_DELETED = 'PANEL_LAYOUT_CONFIGURATION_DELETED'
}
