export type EventType = PanelEventType | StatusMessageEventType

export enum PanelEventType {
  PANEL_LAYOUT_CONFIGURATION_CREATED = 'PANEL_LAYOUT_CONFIGURATION_CREATED',
  PANEL_LAYOUT_CONFIGURATION_UPDATED = 'PANEL_LAYOUT_CONFIGURATION_UPDATED',
  PANEL_LAYOUT_CONFIGURATION_DELETED = 'PANEL_LAYOUT_CONFIGURATION_DELETED',

  PANEL_CONFIGURATION_CREATED = 'PANEL_CONFIGURATION_CREATED',
  PANEL_CONFIGURATION_UPDATED = 'PANEL_CONFIGURATION_UPDATED',
  PANEL_CONFIGURATION_DELETED = 'PANEL_CONFIGURATION_DELETED'
}

export enum StatusMessageEventType {
  STATUS_MESSAGE = 'STATUS_MESSAGE'
}
