name: 'Check'
run-name: 'Test, build, lint and validate'

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  status:
    uses: tv2/ag-github-actions/.github/workflows/status-check.yml@v0.3.0
    with:
      node-version: '20'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}